version: "2"

services:
  api:
    container_name: "yousician-test-api"
    build:
      context: ./api
    ports:
      - "80:5000"
      - "443:443"
    volumes:
      - ./api:/backend-api
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    container_name: "yousician-test-mongodb"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    ports:
      - "27017:27017"
    networks:
      - backend

  db_seed:
    build: ./db-seed
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DBNAME=${MONGO_DBNAME}
    links:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge
