apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 5000
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
