apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-seed
  name: db-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-seed
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kompose
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: db-seed
    spec:
      containers:
        - env:
            - name: MONGO_DBNAME
              value: music
            - name: MONGO_PASSWORD
              value: password
            - name: MONGO_USERNAME
              value: root
          image: lyonsun/yousician-test-db-seed
          imagePullPolicy: ""
          name: db-seed
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
